services:
  mongodb:
    build: .
    container_name: my-mongo-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: eventDB
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: